Plug 'Raimondi/delimitMate'
Plug 'Yggdroot/indentLine'
Plug 'ajh17/VimCompletesMe'
Plug 'altercation/vim-colors-solarized'
Plug 'bling/vim-airline'
Plug 'hvdang/hardmode'
Plug 'junegunn/vim-easy-align', { 'on': 'EasyAlign' }
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/scratch.vim'
